### ISSUE TITLE
WRONG

### ISSUE THREAD

**Issue by CauchyIntegrah** [Florian-Barthel/splatviz#23]
imgui is written in CPP, it is not a native Python library. Reference to README.md

**Comment by BenMcAvoy** [comment]
Is this referring to the comment in the README?
> "This interactive viewer allows you to display and edit 3D Gaussian Splatting scenes in real time. By using a native python GUI library (imgui)"

**Comment by CauchyIntegrah** [comment]
> Is this referring to the comment in the README?
> 
> > "This interactive viewer allows you to display and edit 3D Gaussian Splatting scenes in real time. By using a native python GUI library (imgui)"

Yes.

**Comment by BenMcAvoy** [comment]
Could you make a pull request?

**Comment by CauchyIntegrah** [comment]
Added Fix in PR #24

**Comment by Florian-Barthel** [comment]
Splatviz is using pyimgui (https://pyimgui.readthedocs.io/en/latest/reference/imgui.core.html), which is a python wrapper for the cpp library imgui. I was just referring to pyimgui as imgui, since this is the package name when installing it with pip and when using it in the code. Nevertheless, calling it a native python library is WRONG :). That is true and I will change that.

I just wanted to empathize that there is no other programming language involved for developing and running splatviz (like a js frontend or some cpp files that have to be compiled as in the SIBR viewer).

I hope this resolves this issue!

**Comment by Florian-Barthel** [comment]
I will close this issue for now. Feel free to reopen it, if you think it is still WRONG.
